### ISSUE TITLE
#harmony and es6 features

### ISSUE THREAD

**Issue by BobbyKostadinov** [areusjs/load-common-gulp-tasks#12]
Hi guys,

Writing some code with es6 features (generators) fails silently to run "gulp test-cover".
It would seem that adding --harmony doesn't help and I've found out that Istanbul -> gulp-istanbul support a harmony branch for those of us that want to play with es6 features before they become stable

Gulp Istanbul harmony branch: https://github.com/thejameskyle/gulp-istanbul/tree/harmony
Same project's issue for creating their branch: https://github.com/SBoudrias/gulp-istanbul/issues/30

I've forked this repo and created a harmony branch by just updating the package.json.
I've included my fork as dependance in my project and test-cover works again with node 0.11.15 and es6 generators. 
This is my fork:  https://github.com/BobbyKostadinov/load-common-gulp-tasks/tree/harmony I can't seem to make a pull request to create a new branch. I hope more and more developers start using es6 features so this might be useful to more people

Thanks
Bobby

**Comment by chmontgomery** [comment]
This will be a common problem with other tasks too, like lint. Perhaps we should add an option that puts all tasks into a given mode?

```
require('load-common-gulp-tasks')(gulp, {
   harmony: true
});
```

Unfortunately there are a lot of different [harmony flags](https://github.com/joyent/node/wiki/ES6-%28a.k.a.-Harmony%29-Features-Implemented-in-V8-and-Available-in-Node), so supporting every variation would be too much.

What do you think of that?

**Comment by chmontgomery** [comment]
@BobbyKostadinov also, I can add you to areus and you can add your branch directly into the repo

**Comment by BobbyKostadinov** [comment]
I've ran gulp ci fine on my project (including lint) - the only problem was Istanbul.
Perhaps the other packages support the flag . I am running it with 
    gulp ci --harmony

Not sure about adding harmony settings specifically as if you use iojs you wouldn't need it as they support es6 by default (So I hear)

**Comment by chmontgomery** [comment]
Given that, I'd prefer to leave the code as is (this most common case I think) and allow people to override the individual test-cover task if they wish to use the harmony functionality. The thing missing is just some documentation about this situation.

That said, I still think it's useful to push your change as a separate branch into the main repo for reference.
